#pragma once
#define CW_WINDOW_CLASS_NAME "MainWindowClass"
#define CW_WINDOW_NAME "WinApp"

#define CW_WINDOW_WIDTH 500
#define CW_WINDOW_HEIGHT 300

#define CW_TRACKBAR_WIDTH CW_WINDOW_WIDTH-5
#define CW_TRACKBAR_HEIGHT (int)(CW_WINDOW_HEIGHT/10.0)
#define CW_TRACKBAR_X -5
#define CW_TRACKBAR_Y (int)(CW_WINDOW_HEIGHT/2.0)

